export const tasksAdded = 'tasksAdded'
export const taskAdded = 'taskAdded'
export const taskRemoved = 'taskRemoved'
export const reminderToggled = 'reminderToggled'
export const buttonToggled = 'buttonToggled'
