export const tasksAdded = 'tasksAdded'
export const taskAdded = 'taskAdded'
export const taskRemoved = 'taskRemoved'
export const reminderChanged = 'reminderChanged'
export const buttonToggled = 'buttonToggled'
